apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-deployment
  namespace: flux-system
  labels:
    app: sample-webapp
spec:
  selector:
    matchLabels:
      app: sample-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
      - name: sample-webapp-container
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80