apiVersion: v1
kind: Service
metadata:
  name: sample-webapp-svc
  namespace: flux-system
  labels:
    apps: sample-webapp
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sample-webapp